# - Try to locate QuickTime
# This module defines:
#
#  QUICKTIME_INCLUDE_DIR
#  QUICKTIME_LIBRARY
#  QUICKTIME_FOUND
#

FIND_PATH(QUICKTIME_INCLUDE_DIR NAMES lqt/lqt.h)

FIND_LIBRARY(QUICKTIME_LIBRARY NAMES quicktime)

IF(QUICKTIME_INCLUDE_DIR AND QUICKTIME_LIBRARY)
	SET(QUICKTIME_FOUND TRUE)
ENDIF(QUICKTIME_INCLUDE_DIR AND QUICKTIME_LIBRARY)

IF(QUICKTIME_FOUND)
	IF(NOT QUICKTIME_FIND_QUIETLY)
		MESSAGE(STATUS "Found libquicktime: -I${QUICKTIME_INCLUDE_DIR}, ${QUICKTIME_LIBRARY}")
	ENDIF(NOT QUICKTIME_FIND_QUIETLY)
ELSE(QUICKTIME_FOUND)
	IF(QUICKTIME_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find libquicktime")
	ENDIF(QUICKTIME_FIND_REQUIRED)
ENDIF(QUICKTIME_FOUND)

MARK_AS_ADVANCED(QUICKTIME_INCLUDE_DIR QUICKTIME_LIBRARY QUICKTIME_FOUND)
